### ISSUE TITLE
GPU Manager API Refactor

### ISSUE THREAD

**Issue by kvu35** [gatech-sysml/modin#8]
Since most functions exposed in the gpu manager layer are unecessary, refactor the GPU Manager APIs and code from the query compiler layer downwards to inherit from its base 

Proposal, we should have the following APIs after the refactor:
- `apply_non_persistent(list[int], list[oids], func, **kwargs)`
- `apply(list[int], list[oids], func, **kwargs)`
- `reduce({list[int], list[oids]}, func, **kwargs)`
- `get_oid(int)`
- `put(pandas.DataFrame)`
- `free(int)`
- `get_id()`

Currently the gpu manager has the following apis, so the refactor must support all of the below apis. Here are the equivalent to the old apis.
- `length` == `apply_non_persistent(int, None, lambda x: x.length,**kwargs)`
- `width` == `apply_non_persistent(int, None, lambda x: x.width, **kwargs)`
- `apply` == `apply(int, None, func, **kwargs)`
- `apply_result_not_dataframe` == `apply_non_persistent(int, None, func,**kwargs)`
- `apply_with_one_key_and_object_id` == `apply(int, oid, func, **kwargs)`
- apply_with_two_keys
- reduce_key_list
- brute_force_merge
- reduce
- put
- get
- get_object_id
- to_pandas
- free
- get_id
- apply_with_key_oid_list

**Comment by xiwen1995** [comment]
@kvu35 @pastranakike 

- I think we first want to make sure all the old APIs can be supported by the new APIs.
- Another crucial question is whether to keep the internal dictionary, which previously served as an in-process on-device object store.

**Comment by xiwen1995** [comment]
@kvu35 Do you think we should rename this issue as "GPU Manager Layer Refactor"?
